# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
